### ISSUE TITLE
Appears not to support optional arguments

### ISSUE THREAD

**Issue by iainrb** [oicr-gsi/gsi-wdl-tools#2]
TL;DR Having a File? argument instead of File appears to cause an error.

See attached text file for details of setup on my desktop Ubuntu box. wdl_doc_gen tests run successfully, but processing the WDL file fails.

[wdl_doc_gen_error.txt](https://github.com/oicr-gsi/wdl_doc_gen/files/4340464/wdl_doc_gen_error.txt)

**Comment by mlaszloffy** [comment]
After some investigation, Iain and I found that miniwdl (the library that wdl_doc_gen uses for parsing WDL files) has strict type checking, so something like `File? x = "default"` needs to be changed to `File x = "default"`.
